server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/venuex_transaction_service}
    username: ${SPRING_DATASOURCE_USERNAME:transaction_user}
    password: ${SPRING_DATASOURCE_PASSWORD:transaction_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

services:
  event:
    base-url: http://localhost:8082
