services:
  postgres:
    image: postgres:latest
    container_name: vx-host-request-db
    restart: always
    environment:
      POSTGRES_DB: vx-host-request-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - host_request_pgdata:/var/lib/postgresql/data

  host-request-service:
    build: .
    container_name: host-request-service
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/vx-host-request-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: supersecretpassword

volumes:
  host_request_pgdata:
