services:
  transaction-service:
    build: .
    container_name: transaction-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transaction-db:5432/venuex_transaction_service
      SPRING_DATASOURCE_USERNAME: transaction_user
      SPRING_DATASOURCE_PASSWORD: transaction_pass

      # IMPORTANT: set this to your Eureka container name + port
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

    networks:
      - host-network

networks:
  host-network:
    external: true
