server:
  port: 8081  

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  application:
    name: venue-service   

  datasource:
    url: jdbc:postgresql://localhost:5432/venue_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
