services:
  authdb:
    image: postgres:15
    container_name: authdb
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "15435:5432"
    volumes:
      - authdb-data:/var/lib/postgresql/data
    networks:
      - networkName
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8084:8084"
    depends_on:
      authdb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authdb:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - networkName

volumes:
  authdb-data:

networks:
  networkName:
    external: true