spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vx-host-request-db
    username: postgres
    password: supersecretpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # server might not exist yet
    register-with-eureka: true
    fetch-registry: true
  instance:
  prefer-ip-address: true
