# Use a lightweight JDK base image
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/venue-service-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your service will run on
EXPOSE 8080

# Command to run the JAR
ENTRYPOINT ["java","-jar","app.jar"]
